const films = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    genre: ["Drama"],
    rating: 9.3,
    synopsis: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    genre: ["Crime", "Drama"],
    rating: 9.2,
    synopsis: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    rating: 9.0,
    synopsis: "When the menace known as The Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    title: "Schindler's List",
    director: "Steven Spielberg",
    year: 1993,
    genre: ["Biography", "Drama", "History"],
    rating: 8.9,
    synopsis: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    title: "The Lord of the Rings: The Return of the King",
    director: "Peter Jackson",
    year: 2003,
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.9,
    synopsis: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    genre: ["Crime", "Drama"],
    rating: 8.9,
    synopsis: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    title: "Fight Club",
    director: "David Fincher",
    year: 1999,
    genre: ["Drama"],
    rating: 8.8,
    synopsis: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    genre: ["Drama", "Romance"],
    rating: 8.8,
    synopsis: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    title: "Inception",
    director: "Christopher Nolan",
    year: 2010,
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.8,
    synopsis: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    title: "The Matrix",
    director: "Lana Wachowski, Lilly Wachowski",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    rating: 8.7,
    synopsis: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 11,
    title: "Goodfellas",
    director: "Martin Scorsese",
    year: 1990,
    genre: ["Biography", "Crime", "Drama"],
    rating: 8.7,
    synopsis: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 12,
    title: "Se7en",
    director: "David Fincher",
    year: 1995,
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.6,
    synopsis: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 13,
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    year: 1991,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.6,
    synopsis: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 14,
    title: "Star Wars: Episode V - The Empire Strikes Back",
    director: "Irvin Kershner",
    year: 1980,
    genre: ["Action", "Adventure", "Fantasy"],
    rating: 8.7,
    synopsis: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
    image: "https://via.placeholder.com/150",
  }
  ];
